language: node_js
sudo: required
services:
  - docker
node_js:
  - "8"
env:
  matrix:
  - DEPLOY_ENVIRONMENT=staging DEPLOY_BRANCH=develop
  - ""
script:
  - if [ -z "${DEPLOY_ENVIRONMENT}" ]; then npm run build && npm test; fi
  - .travis/continuous_deployment.sh
